## Naive Bayes Part 1: Predicting survival from Titanic crash

In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [17]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin'], axis='columns', inplace=True)
df.head()

Pclass     Sex   Age     Fare Embarked  Survived
0       3    male  22.0   7.2500        S         0
1       1  female  38.0  71.2833        C         1
2       3  female  26.0   7.9250        S         1
3       1  female  35.0  53.1000        S         1
4       3    male  35.0   8.0500        S         0

In [18]:
inputs = df.drop('Survived', axis='columns')
inputs.head()

Pclass     Sex   Age     Fare Embarked
0       3    male  22.0   7.2500        S
1       1  female  38.0  71.2833        C
2       3  female  26.0   7.9250        S
3       1  female  35.0  53.1000        S
4       3    male  35.0   8.0500        S

In [19]:
target = df['Survived']
target.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [20]:
sex = pd.get_dummies(inputs['Sex'])
sex.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [21]:
embarked = pd.get_dummies(inputs['Embarked'])
embarked.head()

C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1

In [22]:
inputs = pd.concat([inputs, sex, embarked], axis='columns')
inputs.head()

Pclass     Sex   Age     Fare Embarked  female  male  C  Q  S
0       3    male  22.0   7.2500        S       0     1  0  0  1
1       1  female  38.0  71.2833        C       1     0  1  0  0
2       3  female  26.0   7.9250        S       1     0  0  0  1
3       1  female  35.0  53.1000        S       1     0  0  0  1
4       3    male  35.0   8.0500        S       0     1  0  0  1

**I am dropping male column and one of the embarked columns (S) as well because of dummy variable trap. A single column is enough to represent male v/s female and 2 columns are enough to handle the embarked column.**

In [23]:
inputs.drop(['Sex', 'male', 'Embarked', 'S'], axis='columns', inplace=True)
inputs.head()

Pclass   Age     Fare  female  C  Q
0       3  22.0   7.2500       0  0  0
1       1  38.0  71.2833       1  1  0
2       3  26.0   7.9250       1  0  0
3       1  35.0  53.1000       1  0  0
4       3  35.0   8.0500       0  0  0

In [24]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [26]:
inputs['Age'][:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [28]:
inputs['Age'] = inputs['Age'].fillna(inputs['Age'].mean())
inputs.head()

Pclass   Age     Fare  female  C  Q
0       3  22.0   7.2500       0  0  0
1       1  38.0  71.2833       1  1  0
2       3  26.0   7.9250       1  0  0
3       1  35.0  53.1000       1  0  0
4       3  35.0   8.0500       0  0  0

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.3)

In [31]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [32]:
model.fit(X_train, y_train)

GaussianNB()

In [33]:
model.predict(X_test)

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0], dtype=int64)

In [34]:
model.score(X_test, y_test)

0.7238805970149254

In [35]:
X_test[0:10]

Pclass        Age      Fare  female  C  Q
228       2  18.000000   13.0000       0  0  0
490       3  29.699118   19.9667       0  0  0
627       1  21.000000   77.9583       1  0  0
585       1  18.000000   79.6500       1  0  0
372       3  19.000000    8.0500       0  0  0
747       2  30.000000   13.0000       1  0  0
795       2  39.000000   13.0000       0  0  0
318       1  31.000000  164.8667       1  0  0
139       1  24.000000   79.2000       0  1  0
133       2  29.000000   26.0000       1  0  0

In [36]:
y_test[0:10]

228    0
490    0
627    1
585    1
372    0
747    1
795    0
318    1
139    0
133    1
Name: Survived, dtype: int64

In [37]:
model.predict(X_test[0:10])

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

In [38]:
model.predict_proba(X_test[:10])

array([[9.39966285e-01, 6.00337153e-02],
       [9.77683340e-01, 2.23166595e-02],
       [1.96466972e-02, 9.80353303e-01],
       [1.69272780e-02, 9.83072722e-01],
       [9.73037272e-01, 2.69627276e-02],
       [2.82739266e-01, 7.17260734e-01],
       [9.53287920e-01, 4.67120797e-02],
       [1.66730614e-05, 9.99983327e-01],
       [1.38089858e-01, 8.61910142e-01],
       [2.71510640e-01, 7.28489360e-01]])

**Calculate the score using cross validation**

In [40]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(), X_train, y_train, cv=5)

array([0.84      , 0.76      , 0.768     , 0.80645161, 0.71774194])