In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### Data Preprocessing: Fill NA values with median value of a column.

In [4]:
df.bedrooms.median()

4.0

In [6]:
median_bedrooms = np.floor(df.bedrooms.median())

In [7]:
median_bedrooms

4.0

In [8]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [10]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price) #fit methos is used to train the model using the training dataset

LinearRegression()

In [12]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [14]:
reg.intercept_

221323.00186540408

### Find price of home with 3000 sqr ft. area, 3 bedrooms, 40 years old.

In [15]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [18]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.00186540408

498408.2515740241

### Find price of home with 3000 sqr ft. area, 3 bedrooms, 15 years old.

In [16]:
reg.predict([[3000, 3, 15]])

array([579201.19929613])

In [17]:
112.06244194*3000+23388.88007794*3+-3231.71790863*15+221323.00186540408

579201.199289774

### Find price of home with 2500 sqr ft. area, 4 bedrooms, 5 years old.

In [21]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [23]:
112.06244194*2500+23388.88007794*4+-3231.71790863*5+221323.00186540408

578876.0374840142